[package]
name = "wildcards"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.5"
tokio = { version = "1.32.0", features = ["fs", "macros", "rt"] }
tracing = "0.1.37"
